# Generated by Django 2.0.4 on 2018-05-31 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schdule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy', models.CharField(max_length=50, null=True)),
                ('course_number', models.CharField(max_length=20, null=True)),
                ('course_name', models.CharField(max_length=50, null=True)),
                ('course_list', models.CharField(max_length=20, null=True)),
                ('credit_hour', models.CharField(max_length=20, null=True)),
                ('test_type', models.CharField(max_length=20, null=True)),
                ('teacher', models.CharField(max_length=20, null=True)),
                ('course_week', models.CharField(max_length=20, null=True)),
                ('course_day', models.CharField(max_length=20, null=True)),
                ('course_time', models.CharField(max_length=20, null=True)),
                ('campus', models.CharField(max_length=20, null=True)),
                ('teaching_building', models.CharField(max_length=20, null=True)),
                ('classroom', models.CharField(max_length=20, null=True)),
                ('course_capacity', models.PositiveIntegerField(null=True)),
                ('course_limit', models.CharField(max_length=50, null=True)),
                ('course_start', models.PositiveIntegerField(null=True)),
                ('course_end', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('user_password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_And_Schdule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schdule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schedule.Schdule')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schedule.User')),
            ],
        ),
    ]
